include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "lib/generated/**"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    invalid_assignment: error
    missing_return: error
    dead_code: info
    deprecated_member_use: warning

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_locals: true
    avoid_print: true
    avoid_relative_lib_imports: true
    directives_ordering: true
    cancel_subscriptions: true
    close_sinks: true

formatter:
  page_width: 100
  trailing_commas: preserve
